{% set name = "pytdigest" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytdigest-{{ version }}.tar.gz
  sha256: 573dfee19bb0f26fc1f43d8a571b513f9d8f09ff1add98ce99826357e0070f0d

build:
  skip: true  # [py>=400]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy >=1.19.0
    - pandas >=1.1.0

test:
  imports:
    - pytdigest
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/protivinsky/pytdigest
  summary: Python package for *fast* TDigest calculation.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
